server:
  port: 8002
spring:
  cloud:
    stream:
      binders:   #????????rabbitmq?????
        local-server: #????????????
          type: rabbit #?????????????RabbitMQ????rabbit
          environment:  #????????????????????????
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: admin
                password: 123456
                virtual-host: /test
      bindings:
        test-in-0:
          destination: test.exchange